#!/bin/sh

mkdir lib

cd lib
git clone git://github.com/sebastianbergmann/php-code-coverage.git
git clone git://github.com/sebastianbergmann/php-file-iterator.git
git clone git://github.com/sebastianbergmann/php-text-template.git
git clone git://github.com/sebastianbergmann/php-timer.git
git clone git://github.com/sebastianbergmann/php-token-stream.git
git clone git://github.com/sebastianbergmann/phpunit.git
git clone git://github.com/sebastianbergmann/phpunit-mock-objects.git

cd php-code-coverage && git checkout 1.1 && cd ..
cd phpunit && git checkout 3.6 && cd ..
cd phpunit-mock-objects && git checkout 1.1.1 && cd ..
